services:
  simulator:
    command: "./test_app_a.sh --width=$WIDTH --height=$HEIGHT --config=$CONFIG"
    log_dir: "/tmp/pipeline_imgen"
    workdir: "example"
    watchdog: "stdout"
    watchdog_timeout_s: 180

  processor:
    command: "./test_app_b.sh"
    log_dir: "/tmp/pipeline_b"
    workdir: "example"
    # enable: false
